POST /api/users/register HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "email": "ralf1.pauli@gmail.com",
    "password": "Paoword!23"
}

###
POST /api/users/login HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "email": "ralf.pauli@gmail.com",
    "password": "Passoword!23"
}

###
POST /api/shopping-lists/ HTTP/1.1
Host: localhost:3000
Content-Type: application/json
Content-Length: 27

{
    "name": "Grillen"
}

###
GET /api/shopping-lists/ HTTP/1.1
Host: localhost:3000